Dev
knkoji/sentiment-scraper pull request #4
Opened 2018-02-16 06:44 UTC by knkoji

Wasn't able to do a batch request to Watson API but was able to asynchronously make multiple requests to the Watson API using async.js and send to the front end successfully. 

Next step is to package Watson analysis with individual post data and send to the front end as a package.

2018-02-17 05:25 UTC, malekascha commented on bin/index.js
> +  //   console.log("error: \n");
Remove all this code you've commented out

2018-02-17 05:25 UTC, malekascha commented on simple_server/server.js
> +// let resPack = createResponsePack();
remove comments

2018-02-17 05:27 UTC, malekascha commented on simple_server/server.js
> +              concepts: {},
at what point does the post data get sent to watson?

2018-03-02 00:22 UTC, mickberber requested changes
Break watson and all it's concerns out into a different file from `simple-server`.  The server file should only be concerned with starting the server, not all the watson stuff

2018-03-02 00:22 UTC, mickberber commented on simple_server/server.js
> +const async = require("async");
use single quotes in `.js` files

2018-03-02 00:22 UTC, mickberber commented on simple_server/server.js
>  let watsonNLUV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
why is this a `let`? why would you mutate a required module?

2018-03-02 00:22 UTC, mickberber commented on simple_server/server.js
> +        nlu.analyze(
this is weird formatting and makes it hard to read. consider contructiing your objects in a varriable before passing them as an argument:
```
  const data = {
    // no need to use url: url signature anymore see http://es6-features.org/#PropertyShorthand
    url,
     features: {
       concepts: {},
       keywords: {}
     }
  };

  const analyzeCallback = (error, response) => {
    if (error) {
      console.log(`error: ${error}`);
    } else {
      console.log(Object.keys(response));
      cb(null, response);
     }
  };
  nlu.analyze(data, analyzeCallback);
```

2018-03-02 00:22 UTC, mickberber commented on simple_server/server.js
> +  function WatsonObj() {
nesting these functions like this is really weird, and theres no reason to do it, if you look at them, `WatsonObj` does not rely on anything inside of `createWatson` so it should be moved into a different part of the code.

2018-03-02 00:23 UTC, mickberber commented on simple_server/server.js
> +    postsArray = postsObj.data.children.map((postObj) => {
postsArray has no `let` or `const` declaration, this means it will be put on global scope

2018-03-02 00:51 UTC, knkoji commented on simple_server/server.js
> +const async = require("async");
got it

2018-03-02 00:51 UTC, knkoji commented on simple_server/server.js
>  let watsonNLUV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');
yeah there is no reason for it

2018-03-02 00:52 UTC, knkoji commented on simple_server/server.js
> +  function WatsonObj() {
got it

2018-03-02 00:52 UTC, knkoji commented on simple_server/server.js
> +    postsArray = postsObj.data.children.map((postObj) => {
go it

2018-03-02 00:56 UTC, knkoji commented on simple_server/server.js
> +const async = require("async");
Actually quick question: Should I be putting all Watson concerns into a separate file in the simple-server directory or creating a new directory??

2018-03-02 16:10 UTC, mickberber commented
@knkoji 
probably create a watson directory

2018-03-02 18:08 UTC, knkoji commented
@mickberber I'm guessing I should do the same with the reddit functionality a well huh?

2018-03-02 18:11 UTC, mickberber commented
@knkoji correct. to help keep your project on track and make it easier to get feedback, try opening issues related to bugs/features you want to create

see: https://guides.github.com/features/issues/

2018-03-02 21:48 UTC, knkoji commented
Hey @mickberber can you take a look at my code. I started breaking it down but I'm not sure if I'm doing it right. Thanks

2018-03-02 21:50 UTC, knkoji commented
Word. Thanks for the issues article.

2018-03-02 21:58 UTC, mickberber approved these changes
looking good 👍  much better
keep going!!

2018-03-02 21:58 UTC, mickberber commented on simple_server/server.js
> +      postData.extras = extras;
less lines, easier to understand
```
postData.extras = {
  postId: postObj.data.id
};
```

2018-03-02 21:58 UTC, mickberber commented on simple_server/server.js
> +  let id = req.body.id;
same as above. when creating objects, js has to alot memory for them, creating an object like this:
```
var test = {};
test.butt = 'butt';
```
takes the runtime more computing power than this:
```
var test = {
  butt: 'butt'
};
```
because it creates the object and doesnt have to mutate it

2018-03-02 21:58 UTC, mickberber commented on simple_server/server.js
> +      if (data.type === 'title' || data.type === 'selfTitle') {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch
use a switch statement here:
```
switch(data.type) {
  case 'url':
  case 'title':
  case 'selfTitle':
}
```

2018-03-02 21:58 UTC, mickberber commented on simple_server/server.js
> +      if (postObj.data.post_hint) {
nesting if statements can be hard to read as well. consider doing this:
```
if (postObj.data.post_hint && postObj.data.post_hint === 'link') {
```

you should even take this a step further and guard against an undefined `postObj` or `postObj.data`
```
if (postObj &&
    postObj.data &&
    postObj.data.post_hint === 'link') {
```

2018-03-02 21:58 UTC, mickberber commented on apis/reddit.js
> +function createPostsObj() {
dont nest these, just make one, and do `new PostsObj` wherever you end up using this

2018-03-02 21:58 UTC, mickberber commented on apis/reddit.js
> +        .then(function (user) {
be consistent, use arrow functions everywhere, or nowhere
`(user) => `

2018-03-02 21:58 UTC, mickberber commented on apis/reddit.js
> +          let url = `${this.domain}/r/${sub}/new`;
good

2018-03-02 21:58 UTC, mickberber commented on apis/reddit.js
> +      let id = redditId || process_env.REDDIT_ID;
these can be created at the top of the file out side of the function, function will still have access to them

2018-03-02 21:58 UTC, mickberber commented on apis/watson.js
> +      if(data.type === 'url') {
switch statement for these

2018-03-02 21:58 UTC, mickberber commented on bin/index.js
> +      if (source.url) {
chain these with else if

2018-03-02 21:58 UTC, mickberber commented on bin/index.js
> +        type = 'title';
each of these is duplicated, create a function that sets them and use it in each one

2018-03-02 22:00 UTC, mickberber commented
fix what i wrote about, then merge and create a new branch so this doesn't get too long

2018-03-06 19:12 UTC, knkoji commented
yo @mickberber take look at my last commit I broke everything down and it works on my side. I need to take care of deployment though, Heroku config variables aren't working.. let me know if I could do anything else to make it more modular. I'm taking care of all the other issues you brought up right now.

2018-03-06 20:55 UTC, malekascha commented on apis/watson.js
> +module.exports = new WatsonObj();
I would recommend that you export the WatsonObj function, and instantiate the object inside your main file

2018-03-06 20:57 UTC, malekascha commented on app.js
> +      let pack = [];
Why are you pushing objects with a single key each into an array instead of just having an object with all the keys on it?

2018-03-06 20:59 UTC, malekascha commented on front/index.js
> +        success: displaySentiment
might want to add an error callback in case the ajax request fails

2018-03-07 03:35 UTC, knkoji commented on app.js
> +      let pack = [];
haha. good question I have no idea!

2018-03-07 03:40 UTC, knkoji commented on app.js
> +      let pack = [];
Ok I think I know. Because I have if statements to check to see what type of data lies within and I want to forEach through the array. I'm actively trying to build an array.

2018-03-07 03:41 UTC, knkoji commented on front/index.js
> +        success: displaySentiment
What should it do?

2018-03-07 03:44 UTC, knkoji commented
I'm going to go ahead and close this and focus on getting my config variables working

2018-03-07 03:44 UTC, merged

2018-03-09 03:56 UTC, mickberber commented on app.js
> +      let pack = [];
youre mapping through this. why are you going to for each twice on the front? Youre mapping here, and returning arrays. your data will look like: 
```
[
  [{ url }, { selfText }, { title }],
  [{}, {}, {}],
  [{}, {}, {}],
  [{}, {}, {}],
  [{}, {}, {}],
  [{}, {}, {}]
];
// it would make more sense on the front end to read the object like malek said
// if you know your properties like this you don't need to iterate. this is a lot fast because the object keys give you O(n) lookup
{
  url,
  selfText,
  title
}
```

---

es6 lets you do: `pack.push({ url });`

---

2018-03-09 04:00 UTC, mickberber commented on app.js
> +      return postData;
```javascript
  // this is how i would construct this object
  const url = postObj && postObj.data && postObj.data.post_hint === 'link' ? postObj.data.url : undefined;
  const selfText = postObj.data.selftext;
  return {
    url,
    selfText,
    title: postObj.data.title,
    id: postObj.data.id
  };
```

2018-03-09 04:01 UTC, mickberber commented on app.js
> +      return postData;
worst case scenario, you have an object with undefined properties on the front end, which makes display or hide very easy checks

2018-03-09 04:03 UTC, mickberber commented on app.js
> +      return postData;
and you still have an array

2018-03-13 02:41 UTC, knkoji commented on app.js
> +      return postData;
Yo @mickberber thanks. I've been sick so I haven't been working on it but I feel beeter so Im looking through it right now.

2018-03-13 03:16 UTC, knkoji commented on app.js
> +      return postData;
What about this? 
if (postObj.data) {
        let pack = { title: postObj.data.title };
        if (postObj && postObj.data && postObj.data.post_hint === 'link') {
          let url = postObj.data.url;
          pack.url = url;
        }
        if (postObj.data.selftext) {
          let selfText = postObj.data.selftext;
          pack.selfText = selfText;
        }
      }
      let postData = {
        pack: pack
      }
      postData.extras = {
        postId: postObj.data.id
      }
      return postData;